
package View;

import Controller.Ctrl_Autorizado;
import Controller.Ctrl_Msg;
import Controller.Ctrl_Util;
import Controller.Ctrl_Veiculo;
import Model.Model_Banco;
import Model.Model_Veiculo;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

public class View_CadVeiculo extends javax.swing.JFrame {
    private static boolean EstaEditando = false;
    private static Ctrl_Veiculo Veiculo = new Ctrl_Veiculo();
    public View_CadVeiculo() {
        initComponents();
        CentarlizarTela();
        PopularTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLimpar2 = new javax.swing.JButton();
        btnFechar2 = new javax.swing.JButton();
        btnSalvar2 = new javax.swing.JButton();
        btnDeletar2 = new javax.swing.JButton();
        btnEditar2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbAutorizados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbVaga = new javax.swing.JComboBox<>();
        txtPlaca = new javax.swing.JFormattedTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbVeiculos = new javax.swing.JTable();
        txtCod = new javax.swing.JTextField();
        btnEditar3 = new javax.swing.JButton();
        btnSalvar3 = new javax.swing.JButton();
        btnDeletar3 = new javax.swing.JButton();
        btnLimpar3 = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        btnLimpar2.setText("Limpar");
        btnLimpar2.setToolTipText("Clique aqui para limpar os campos");

        btnFechar2.setText("Fechar");
        btnFechar2.setToolTipText("Clique aqui para fechar os campos");

        btnSalvar2.setText("Salvar");
        btnSalvar2.setToolTipText("Clique aqui para salvar os campos");

        btnDeletar2.setText("Deletar");
        btnDeletar2.setToolTipText("Clique aqui para deletar os campos");

        btnEditar2.setText("Editar");
        btnEditar2.setToolTipText("Clique aqui para editar os campos");

        tbAutorizados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}

            },
            new String [] {
                "ID", "Nome"
            }
        ));
        jScrollPane2.setViewportView(tbAutorizados);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Veículo");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabel1.setText("Cód:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabel2.setText("Placa:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabel3.setText("Tipo Vaga:");

        cbVaga.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        cbVaga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"MOTO", "CARRO"}));

        try
        {
            MaskFormatter maskData = new MaskFormatter("AAA-####");
            maskData.install(txtPlaca);
        }

        catch (Exception erroGenerico)
        {
            String mensagem = "";
            erroGenerico.printStackTrace();
            mensagem = erroGenerico.getMessage();
        }
        txtPlaca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPlaca.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        tbVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {"Código", "Placa", "Tipo"}));
    jScrollPane3.setViewportView(tbVeiculos);

    try {
        txtCod.setText(Model_Banco.BuscaCodigoNovo("VEICULO"));
    } catch (Exception e) {
    }
    txtCod.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
    txtCod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txtCod.setEnabled(false);
    txtCod.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            txtCodFocusLost(evt);
        }
    });
    txtCod.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtCodActionPerformed(evt);
        }
    });

    btnEditar3.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
    btnEditar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/Easyeditar.png"))); // NOI18N
    btnEditar3.setText("Editar");
    btnEditar3.setToolTipText("Clique aqui para editar os campos");
    btnEditar3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnEditar3ActionPerformed(evt);
        }
    });

    btnSalvar3.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
    btnSalvar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/Easysave.png"))); // NOI18N
    btnSalvar3.setText("Salvar");
    btnSalvar3.setToolTipText("Clique aqui para salvar os campos");
    btnSalvar3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSalvar3ActionPerformed(evt);
        }
    });

    btnDeletar3.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
    btnDeletar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/Easyexcluir.png"))); // NOI18N
    btnDeletar3.setText("Excluir");
    btnDeletar3.setToolTipText("Clique aqui para excluir o registro");
    btnDeletar3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnDeletar3ActionPerformed(evt);
        }
    });

    btnLimpar3.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
    btnLimpar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/Easylimpar.png"))); // NOI18N
    btnLimpar3.setText("Limpar");
    btnLimpar3.setToolTipText("Clique aqui para limpar os campos");
    btnLimpar3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnLimpar3ActionPerformed(evt);
        }
    });

    btnFechar.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
    btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/Easyfechar.png"))); // NOI18N
    btnFechar.setText("Fechar");
    btnFechar.setToolTipText("Clique aqui para fechar");
    btnFechar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnFecharActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(10, 10, 10)
                            .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnEditar3)
                    .addGap(5, 5, 5)
                    .addComponent(btnSalvar3)
                    .addGap(5, 5, 5)
                    .addComponent(btnDeletar3)
                    .addGap(5, 5, 5)
                    .addComponent(btnLimpar3)
                    .addGap(5, 5, 5)
                    .addComponent(btnFechar)))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(12, 12, 12)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbVaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGap(0, 14, Short.MAX_VALUE))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnEditar3)
                .addComponent(btnSalvar3)
                .addComponent(btnDeletar3)
                .addComponent(btnLimpar3)
                .addComponent(btnFechar))
            .addGap(14, 14, 14))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodFocusLost

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed

    }//GEN-LAST:event_txtCodActionPerformed

    private void btnEditar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar3ActionPerformed
        boolean r = Verifica();
        if (r==true)
        {
            r =false;
            r =  Ctrl_Msg.Questiona(Ctrl_Msg.MsgQEditar);
            if (r==true)
            {
                Bloqueia(false);
                EstaEditando=true;
            }
        }
    }//GEN-LAST:event_btnEditar3ActionPerformed

    private void btnSalvar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar3ActionPerformed

        boolean r =  Verifica();
        if (r==true)
        {
            r = false;
            r = Ctrl_Msg.Questiona(Ctrl_Msg.MsgQSalvar);
            if (r==true)
            {

                try
                {
                    Atribuir(true);
                    String CodNew =  Model_Veiculo.Salvar(Veiculo);
                    Limpar();
                    LimparTabela();
                    PopularTabela();
                    txtCod.setText(CodNew);
                    Ctrl_Msg.Informa(Ctrl_Msg.MsgISalvo);
                }
                catch (Exception e)
                {
                    Ctrl_Msg.Informa(Ctrl_Msg.MsgErro);
                }
            }

        }
    }//GEN-LAST:event_btnSalvar3ActionPerformed

    private void btnDeletar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletar3ActionPerformed
        if (EstaEditando==true)
        {
            boolean r =  Ctrl_Msg.Questiona(Ctrl_Msg.MsgQDeletar);
            if (r==true) {
                //metodo de excluir
            }
        }
        else
        {
            Ctrl_Msg.Informa(Ctrl_Msg.MsgIEdicao);
        }
    }//GEN-LAST:event_btnDeletar3ActionPerformed

    private void btnLimpar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar3ActionPerformed

        boolean r =  Ctrl_Msg.Questiona(Ctrl_Msg.MsgQLimpar);
        if (r==true)
        {
            Limpar();
        }
    }//GEN-LAST:event_btnLimpar3ActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed

        boolean r =  Ctrl_Msg.Questiona(Ctrl_Msg.MsgQFechar);
        if (r==true)
        {
            this.dispose();

        }
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_CadVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_CadVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_CadVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_CadVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_CadVeiculo().setVisible(true);
            }
        });
    }
    public void centralizarComponente() 
    {
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = getSize();
        setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletar2;
    private javax.swing.JButton btnDeletar3;
    private javax.swing.JButton btnEditar2;
    private javax.swing.JButton btnEditar3;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnFechar2;
    private javax.swing.JButton btnLimpar2;
    private javax.swing.JButton btnLimpar3;
    private javax.swing.JButton btnSalvar2;
    private javax.swing.JButton btnSalvar3;
    private javax.swing.JComboBox<String> cbVaga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbAutorizados;
    private javax.swing.JTable tbVeiculos;
    private javax.swing.JTextField txtCod;
    private javax.swing.JFormattedTextField txtPlaca;
    // End of variables declaration//GEN-END:variables

    private void Limpar(){
        txtCod.setText("");
        txtPlaca.setText("");
        cbVaga.setSelectedIndex(0);
    }
    
    private void Bloqueia (boolean Bloqueiar)
    {
        if (Bloqueiar == true) 
        {
            txtPlaca.setEnabled(false);
            cbVaga.setEnabled(false);
           
        }
        else
        {
            txtPlaca.setEnabled(true);
            cbVaga.setEnabled(true);
           
        }
          
    }

    
    private void Atribuir(boolean Vai)
    {
        if (Vai==true) {
            Veiculo.setId(txtCod.getText());
            Veiculo.setPlaca(txtPlaca.getText());
            Veiculo.setIdTipoVaga((cbVaga.getSelectedItem().equals("CARRO"))? "1":"2");
            Veiculo.setIdMotorista(Ctrl_Util.IdCliente);           
        }
        else
        {
            txtCod.setText(Veiculo.getId());
            txtPlaca.setText(Veiculo.getPlaca());
            cbVaga.setSelectedIndex(Integer.parseInt(Veiculo.getIdTipoVaga()));
        }

    }
    
    private  boolean Verifica()
    {
        String x[] = new String[4];
        x[0] = txtCod.getText();
        x [1] = txtPlaca.getText();
        x [2] = String.valueOf(cbVaga.getSelectedIndex());
        x [3] = Ctrl_Util.IdCliente;
        
        
        for (int i = 0; i < 4; i++) {
            if(x[i].equals(""))
            {
                Ctrl_Msg.Informa(Ctrl_Msg.MsgICampos);
                return false; 
            }
        }
        return true;
    }
    
    

    private void CentarlizarTela() {
    
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = getSize();
        setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    
    }
    
    private void PopularTabela() {
        List<Ctrl_Veiculo> ListaDeVeiculos = Model.Model_Veiculo.Busca(Ctrl_Util.IdCliente);
        
        DefaultTableModel model = (DefaultTableModel) tbVeiculos.getModel();
        for (int i = 0; i < ListaDeVeiculos.size(); i++) {
            String Tipo = (ListaDeVeiculos.get(i).getIdTipoVaga().equals("1"))? "Carro" : "Moto";
            Object[] linha = {ListaDeVeiculos.get(i).getId(),ListaDeVeiculos.get(i).getPlaca(), Tipo};
            model.addRow(linha);
        }
        tbVeiculos.setModel(model);
    }
    
    private void LimparTabela(){
        tbVeiculos.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {},
        new String [] {"Código", "Placa", "Tipo"}));
    }
}


