/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Ctrl_Autorizado;
import Controller.Ctrl_Cliente;
import Controller.Ctrl_Msg;
import Controller.Ctrl_Util;
import Controller.Ctrl_Venda;
import Model.Model_Vaga;
import Model.Model_Venda;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;


public class View_VendaFinalizar extends javax.swing.JFrame {

    
    public View_VendaFinalizar() {
        initComponents();
        centralizarComponente();
        rbtCodVenda.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupConCliente = new javax.swing.ButtonGroup();
        txtFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dtgConVenda = new javax.swing.JTable();
        rbtCodCliente = new javax.swing.JRadioButton();
        btnFinalizar = new javax.swing.JButton();
        rbtCodVenda = new javax.swing.JRadioButton();
        btnFechar = new javax.swing.JButton();
        btnAnular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Clientes");
        setResizable(false);

        txtFiltro.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        txtFiltro.setForeground(java.awt.Color.lightGray);
        txtFiltro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFiltro.setText("Informe o código da venda");
        txtFiltro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFiltroFocusGained(evt);
            }
        });
        txtFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFiltroMouseClicked(evt);
            }
        });
        txtFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltroActionPerformed(evt);
            }
        });
        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFiltroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFiltroKeyTyped(evt);
            }
        });
        txtFiltro.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                txtFiltroVetoableChange(evt);
            }
        });

        dtgConVenda.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        dtgConVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Cód Venda","Vaga", "Staus", "Id Pessoal"
            }
        ));
        dtgConVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtgConVendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dtgConVenda);
        if (dtgConVenda.getColumnModel().getColumnCount() > 0) {
            dtgConVenda.getColumnModel().getColumn(0).setMinWidth(80);
            dtgConVenda.getColumnModel().getColumn(0).setPreferredWidth(70);
            dtgConVenda.getColumnModel().getColumn(0).setMaxWidth(90);
        }

        groupConCliente.add(rbtCodCliente);
        rbtCodCliente.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        rbtCodCliente.setText("Código do Cliente");
        rbtCodCliente.setSelected(true);
        rbtCodCliente.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtCodClienteStateChanged(evt);
            }
        });
        rbtCodCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtCodClienteActionPerformed(evt);
            }
        });

        btnFinalizar.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        btnFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/encerrar.png"))); // NOI18N
        btnFinalizar.setText("Finalizar");
        btnFinalizar.setToolTipText("Clique aqui para fechar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        groupConCliente.add(rbtCodVenda);
        rbtCodVenda.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        rbtCodVenda.setSelected(true);
        rbtCodVenda.setText("Código da Venda");
        rbtCodCliente.setSelected(true);
        rbtCodVenda.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtCodVendaStateChanged(evt);
            }
        });
        rbtCodVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtCodVendaActionPerformed(evt);
            }
        });

        btnFechar.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/Easyfechar.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.setToolTipText("Clique aqui para fechar");

        btnAnular.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        btnAnular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/a3.png"))); // NOI18N
        btnAnular.setText("Anular");
        btnAnular.setToolTipText("Clique aqui para fechar");
        btnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAnular)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnFinalizar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnFechar))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtCodCliente)
                    .addComponent(rbtCodVenda))
                .addGap(18, 18, 18)
                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizar)
                    .addComponent(btnFechar)
                    .addComponent(btnAnular))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltroActionPerformed

    private void rbtCodClienteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtCodClienteStateChanged
      
    }//GEN-LAST:event_rbtCodClienteStateChanged

    private void rbtCodClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtCodClienteActionPerformed
        MudarTexto();
    }//GEN-LAST:event_rbtCodClienteActionPerformed

    private void txtFiltroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFiltroMouseClicked
       txtFiltro.setText("");
       txtFiltro.setForeground(Color.black);
        
    }//GEN-LAST:event_txtFiltroMouseClicked

    private void txtFiltroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFiltroFocusGained
       txtFiltro.setText("");
       txtFiltro.setForeground(Color.black);
    }//GEN-LAST:event_txtFiltroFocusGained

    private void txtFiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyPressed

    }//GEN-LAST:event_txtFiltroKeyPressed

    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
        Limpar();
        Popular();
    }//GEN-LAST:event_txtFiltroKeyReleased

    private void txtFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyTyped
        
    }//GEN-LAST:event_txtFiltroKeyTyped

    private void txtFiltroVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_txtFiltroVetoableChange

    }//GEN-LAST:event_txtFiltroVetoableChange

    private void rbtCodVendaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtCodVendaStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtCodVendaStateChanged

    private void rbtCodVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtCodVendaActionPerformed
        MudarTexto();
    }//GEN-LAST:event_rbtCodVendaActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
       
       int l = dtgConVenda.getSelectedRow();
       String  venda = (String) dtgConVenda.getValueAt(l,0);
       String  vaga = (String) dtgConVenda.getValueAt(l,1);
       
        try {
            Model_Venda.SetStatusVenda(venda , "0");
            Model_Vaga.SetStatusVaga(vaga , "0");
            
        } catch (SQLException ex) {
          
        }
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void dtgConVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtgConVendaMouseClicked
        
    }//GEN-LAST:event_dtgConVendaMouseClicked

    private void btnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularActionPerformed
     int l = dtgConVenda.getSelectedRow();
       String  venda = (String) dtgConVenda.getValueAt(l,0);
       String  vaga = (String) dtgConVenda.getValueAt(l,1);
       
        try {
            Model_Venda.SetStatusVenda(venda , "2");
            Model_Vaga.SetStatusVaga(vaga , "0");
            
        } catch (SQLException ex) {
          
        }
    }//GEN-LAST:event_btnAnularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_VendaFinalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_VendaFinalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_VendaFinalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_VendaFinalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_VendaFinalizar().setVisible(true);
            }
        });
    }
    
    public void centralizarComponente() 
    {
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = getSize();
        setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JTable dtgConVenda;
    private javax.swing.ButtonGroup groupConCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtCodCliente;
    private javax.swing.JRadioButton rbtCodVenda;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables

    private void MudarTexto() {
        txtFiltro.setForeground(Color.LIGHT_GRAY);
        if (rbtCodVenda.isSelected()==true) 
        {
            txtFiltro.setText("Informe o código da venda");
        }
        else if (rbtCodCliente.isSelected()==true)
        {
            txtFiltro.setText("Informe o código do cliente");
        }
              
        
    }
    
    private void Limpar(){
        dtgConVenda.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {},
        new String [] {"Cód Venda","Vaga", "Staus", "Id Pessoal"}));
    }
    private void Popular(){
        
        List<Ctrl_Venda> ListaVenda = new ArrayList<Ctrl_Venda>();
        if (rbtCodVenda.isSelected()==true) 
        {
            ListaVenda =  Model_Venda.Busca(txtFiltro.getText(), 0);
        }
        else{
            ListaVenda =  Model_Venda.Busca(txtFiltro.getText(), 1); 
        }
          
        DefaultTableModel model = (DefaultTableModel) dtgConVenda.getModel();
        for (int i = 0; i < ListaVenda.size(); i++) {
            Object[] linha = {ListaVenda.get(i).getId(), ListaVenda.get(i).getId_Vaga() , ListaVenda.get(i).getStatus(), ListaVenda.get(i).getId_Motorista()};
            model.addRow(linha);
        }
        dtgConVenda.setModel(model);
    }

    


}


